# -*- coding: utf-8 -*-
"""connect4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1-erFPzjuAZjjCTo5o7vCl1aNRnhGkw
"""

import Double2

Double2.sqroot(5)