# -*- coding: utf-8 -*-
"""double3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1-erFPzjuAZjjCTo5o7vCl1aNRnhGkw
"""

def sqroot(x):
  return x**.5